# Generated by Django 5.0.6 on 2026-08-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_verified_user_otp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text="Job Description including required skills. Add a 'Skills:' section with comma-separated skills, e.g. Skills: Python, Django, SQL, Machine Learning"),
        ),
    ]
