# Generated by Django 5.0.6 on 2026-08-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_job_required_skills_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, help_text='Password reset token', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_created',
            field=models.DateTimeField(blank=True, help_text='When the reset token was created', null=True),
        ),
    ]
