# Generated by Django 5.0.6 on 2026-08-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_reset_token_user_reset_token_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, help_text='When the OTP was created', null=True),
        ),
    ]
