# Generated by Django 5.0.6 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, default='Your Company', help_text='Company / Organization name', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='cutoff_score',
            field=models.FloatField(default=75.0, help_text='Passing score percentage for shortlisting (e.g. 75.0)'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.PositiveIntegerField(default=0, help_text='Minimum years of experience required (0 for any)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_years',
            field=models.FloatField(default=0.0, help_text='Estimated years of experience'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='github_url',
            field=models.URLField(blank=True, help_text='Candidate GitHub profile'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Candidate LinkedIn profile'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Portfolio / Website'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notes',
            field=models.TextField(blank=True, help_text='Recruiter internal notes & evaluation'),
        ),
        migrations.AddField(
            model_name='score',
            name='experience_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='score',
            name='status',
            field=models.CharField(
                choices=[
                    ('applied', 'Applied'),
                    ('screened', 'Screened'),
                    ('shortlisted', 'Shortlisted'),
                    ('interview', 'Interview'),
                    ('technical', 'Technical Round'),
                    ('offered', 'Offered'),
                    ('hired', 'Hired'),
                    ('rejected', 'Rejected'),
                ],
                default='screened',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
