# Generated by Django 6.1 on 2026-08-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_job_company_name_job_cutoff_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, help_text='Hashed OTP storage', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, help_text='Hashed password reset token', max_length=255),
        ),
    ]
